steps:
# Access the secret
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: [ '-c', "gcloud secrets versions access latest --secret=faster-backend-env-file > .env"]

# Build the container images
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '-t', 
    'gcr.io/$PROJECT_ID/faster-backend:$COMMIT_SHA', '.'
  ]

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/faster-backend:$COMMIT_SHA']

# Deploy Container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - "run"
    - "deploy"
    - "faster-backend"
    - "--image"
    - "gcr.io/$PROJECT_ID/faster-backend:$COMMIT_SHA"
    - "--region"
    - "us-central1"
    - "--platform"
    - "managed"
images:
  - "gcr.io/$PROJECT_ID/faster-backend:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
  # Use the deterrence-pool Cloud Build pool
  pool:
    name: "projects/$PROJECT_ID/locations/us-central1/workerPools/deterrence-pool"
